// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cwqyuusovmayeiykibbv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3cXl1dXNvdm1heWVpeWtpYmJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4OTU0NzIsImV4cCI6MjA2MjQ3MTQ3Mn0.CbhRz_xmBHQlLADi0VbVYRMo5ASCuJ1Q7clVyLfbxrI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);